#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK  GPIO_NUM_19
#define AUDIO_I2S_GPIO_WS    GPIO_NUM_22
#define AUDIO_I2S_GPIO_BCLK  GPIO_NUM_21
#define AUDIO_I2S_GPIO_DIN   GPIO_NUM_20
#define AUDIO_I2S_GPIO_DOUT  GPIO_NUM_23

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_18
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_8
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_9
#define VBAT_PWR_GPIO           GPIO_NUM_2
#define BATTERY_ADC_PIN         GPIO_NUM_0

/*EPD port Init*/
#define EPD_SPI_NUM        SPI2_HOST

#define EPD_DC_PIN    GPIO_NUM_15
#define EPD_CS_PIN    GPIO_NUM_7
#define EPD_SCK_PIN   GPIO_NUM_6
#define EPD_MOSI_PIN  GPIO_NUM_5
#define EPD_RST_PIN   GPIO_NUM_11
#define EPD_BUSY_PIN  GPIO_NUM_10

#define EXAMPLE_LCD_WIDTH   200
#define EXAMPLE_LCD_HEIGHT  200
 
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0



#endif // _BOARD_CONFIG_H_
